#!/bin/sh

killall "picom"
picom & 
feh --bg-scale ~/pictures/wallpapers/current-wallpaper

killall "sxhkd"
sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width 1
bspc config normal_border_color "#0c0c59"
bspc config focused_border_color "#6565F5"
bspc config window_gap 8

# start polybar
killall "polybar"
polybar bspwm
