#!/bin/sh

# Set the keyboard layout
setxkbmap -layout us -variant coding 

# establish tmp dir for sxhkd
test -z /tmp/sxhkd && mkdir /tmp/sxhkd

killall "picom"
picom & 
feh --bg-scale ~/pictures/wallpaper/current-wallpaper

killall "sxhkd"
sxhkd -c ~/.config/sxhkd/sxhkdrc &

killall "polybar"
polybar -r bspwm &

killall "redshift"
redshift -l 35:-78 &

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9 0 

bspc config border_width 2
bspc config window_gap 0
bspc config normal_border_color "#040430"
bspc config focused_border_color "#4555FF"
bspc config single_monocle true
bspc config borderless_monocle true


# shouldn't have a dep like this... will work on it
ISZEN= $(<~/.config/sxhkd/.is-zenr
if [ "$ISZEN" = "true"]; then 
	bspc config bottom_padding 130
	bspc config window_gap 0
else
	bspc config window_gap 0
	bspc config bottom_padding 0 # not needed but consistent
fi


# start polybar
killall "polybar"
polybar bspwm
